INHERIT: .provide/foundry/base-mkdocs.yml
site_name: Plating
site_description: Documentation and code generation templates
site_author: provide.io
site_url: https://foundry.provide.io/plating/
repo_url: https://github.com/provide-io/plating
repo_name: provide-io/plating
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024-2025 provide.io
dev_addr: 127.0.0.1:8009
docs_dir: docs
theme:
  font:
    text: Inter
    code: Fira Code
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: black
    accent: deep purple
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: indigo
    accent: deep purple
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
nav:
- Overview: index.md
- null:
    Resources:
      readme: resources/readme.md
- Core Components:
    Resources:
      adorner: resources/adorner.md
